openapi: 3.0.0
info:
  title: Sentiment Analysis API
  version: 1.0.0
paths:
  /predict:
    post:
      summary: Predict sentiment and extract entities from a text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
      responses:
        '200':
          description: Sentiment prediction and entity extraction
          content:
            application/json:
              schema:
                type: object
                properties:
                  entity_list:
                    type: array
                    items:
                      type: string
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        entity:
                          type: string
                        sentiment:
                          type: string
